### ISSUE TITLE
Votes score undefined

### ISSUE THREAD

**Issue by BlueskyFR** [goto-bus-stop/miniplug#111]
Hi!
I'm using miniplug to set up my bot, and I am facing an issue. After registering this :
`mp.on('advance', eventAdvance);`
and
`function eventAdvance(next, previous) {
    console.log(previous.score.positive);
}`
I have an error telling me that `previous.score` is undefined.

Please answer me ASAP, thanks :)

**Comment by Burkes** [comment]
The score maintained by miniplug would always be different than the one by plug for weird reasons, so it's best to retrieve it via `mp.getRoomHistory()` once the song advances. I can see why you ran into that, the documentation doesn't specify the availability of `score` (same for `room` though).
