### ISSUE TITLE
Implement/Document socket events

### ISSUE THREAD

**Issue by goto-bus-stop** [goto-bus-stop/miniplug#21]
List from [plug-socket](https://npm.im/plug-socket#events):

- [x] ack
- [x] advance
- [x] ban
- [ ] banIP
- [x] chat
- [x] chatDelete
- [x] djListCycle
- [x] djListLocked
- [x] djListUpdate
- [x] earn
- [x] sub
- [ ] cash
- [x] gift
- [ ] floodChat
- [ ] floodAPI
- [x] friendRequest
- [x] friendAccept
- [x] gifted
- [x] grab
- [ ] killSession
- [x] modBan
- [x] modAddDJ
- [x] modRemoveDJ
- [x] modMoveDJ
- [x] modMute
- [x] modSkip
- [x] modStaff
- [ ] nameChanged
- [ ] nameChangedRoom
- [x] notify
- [x] playlistCycle
- [x] plugMaintenance
- [x] plugMaintenanceAlert
- [x] plugMessage
- [x] plugUpdate
- [ ] rateLimit
- [x] roomNameUpdate
- [x] roomDescriptionUpdate
- [x] roomWelcomeUpdate
- [x] roomMinChatLevelUpdate
- [x] skip
- [x] userJoin
- [x] userLeave
- [x] userUpdate
- [x] vote

**Comment by cosmetify** [comment]
Don't forget to check the ones I got x)

I'll try to cover all the simple ones.

**Comment by cosmetify** [comment]
skip has been implemented

**Comment by goto-bus-stop** [comment]
The remaining events are not that useful and extremely rare so I'm okay with missing out on them & addressing in separate issues if someone needs them anyway.
