### ISSUE TITLE
Seemingly no way to get the response body on error

### ISSUE THREAD

**Issue by Burkes** [goto-bus-stop/miniplug#37]
I need to get the body of the error when `mp.addDJ` fails, to parse the error message returned.

Example:
```javascript
{
    "data": ["This request was understood but is forbidden."],
    "meta": {},
    "status": "noValidPlaylist",
    "time": 12.279033660888672
}
```

But there doesn't seem to be any way to get it through `Promise.catch` or the second `Promise.then` parameter. All I get is the native HTTP Error which isn't very useful.

Sorry if I missed a very obvious way of doing this.

**Comment by goto-bus-stop** [comment]
Yeah this does need to be better. Right now you can access the response object from [`got`](https://npm.im/got) on the `response` property:

```js
mp.addDJ(xyz).catch((err) => {
  console.log(err.response.body)
})
```
