### ISSUE TITLE
Add an event when the socket connection ends

### ISSUE THREAD

**Issue by cosmetify** [goto-bus-stop/miniplug#47]
Just the other day, plug was having issues with advancing and whatnot. When the site went down (or perhaps before?), my bot didn't get any type of error, plugMait, etc. event. It just stopped receiving all events from plug.

This is an issue since my bot had no way of knowing plug was down and therefore couldn't auto restart. There should be some kind of timeout where it'll emit an event that there haven't been any events from plug after x amount of time. (probably 30s~1m)

**Comment by goto-bus-stop** [comment]
You can do

```js
mp.ws.on('close', (code, reason) => {
  // etc
})
```

because `mp.ws` is an instance of [ws](https://www.npmjs.com/package/ws).

But it's probably easier if we also emit something like `disconnected` on the miniplug instance.
