### ISSUE TITLE
Check for Socket Connection after Login

### ISSUE THREAD

**Issue by cosmetify** [goto-bus-stop/miniplug#60]
Sometimes (often when plug is having issues) the bot can login but not connect to the socket. This leaves the bot useless and if you run stuff like forever monitor, your bot won't reconnect.

Perhaps a constant monitor of events to make sure the bot is connected could be a method to fix this. Or maybe some type of check after login.

**Comment by goto-bus-stop** [comment]
> the bot can login but not connect to the socket.

Do you know if the connection fails entirely, or if the socket connects but never sends any data? The first is a bit easier to deal with :eyes: Although …

> Perhaps a constant monitor of events to make sure the bot is connected could be a method to fix this. Or maybe some type of check after login.

… I guess we should check for the `h`eartbeats either way.

**Comment by cosmetify** [comment]
>Do you know if the connection fails entirely, or if the socket connects but never sends any data? The first is a bit easier to deal with 👀 Although …

Pretty sure it's the second, because I get the two `login` and `connected` events, then it joins the room successfully.

Though now it'll be difficult to test since it seems plug has fixed those issues finally.

**Comment by goto-bus-stop** [comment]
https://github.com/goto-bus-stop/plug-socket/commit/f502000a4c850321614558c020d2ded14652ec91 disconnects the socket when a message or a `h`eartbeat has not been received for 25 seconds (normally, they're sent every 10 s). This will fire the `mp.ws.on('close')` event.

#64

**Comment by goto-bus-stop** [comment]
Actually responding to the disconnection by crashing or reconnecting is something to figure out in #47 :)
